### ISSUE TITLE
parse_solver_output task always fails in solver workflows

### ISSUE THREAD

**Issue by fridex** [thoth-station/workflow-helpers#273]
**Describe the bug**

```
Traceback (most recent call last):
  File "parse_solver_output.py", line 24, in <module>
    from thoth.storages import GraphDatabase
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/__init__.py", line 31, in <module>
    from .graph import GraphDatabase
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/__init__.py", line 21, in <module>
    from .postgres import GraphDatabase
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 57, in <module>
    from thoth.python import PackageVersion
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/__init__.py", line 20, in <module>
    from .aiosource import AIOSource
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/aiosource.py", line 26, in <module>
    import aiohttp
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/helpers.py", line 48, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**To Reproduce**
1. Schedule a solver via management-api in test/stage/prod
2. See the error in solver workflow

**Expected behavior**

Solver workflow should succeed.

**Comment by goern** [comment]
/kind bug
/label deployment_name/zero-prod
/label deployment_name/ocp4-stage
/label deployment_name/ocp4-test
/triage needs-information

@fridex feel free to remove triage or reset prior
/priority important-longterm
