### ISSUE TITLE
parse_adviser_output fails in stage environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/workflow-helpers#329]
**Describe the bug**

```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1631608761.5765753, "asctime": "2021-09-14 08:39:21,576", "msecs": 576.5752792358398, "relative_created": 7993.062734603882, "process": 1, "message": "Logging to a Sentry instance is turned off"}
Traceback (most recent call last):
  File "parse_adviser_output.py", line 132, in <module>
    parse_adviser_output()
  File "parse_adviser_output.py", line 104, in parse_adviser_output
    message_input = UnresolvedPackageContents(
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MessageContents
index_url
  none is not an allowed value (type=type_error.none.not_allowed)
```

**To Reproduce**
1. Schedule authenticated request in the stage environment
4. See the error in parse_adviser_output task

**Expected behavior**

No error should be produced.

**Comment by goern** [comment]
is this still valid?

**Comment by KPostOffice** [comment]
@harshad16 Just letting you know. I am taking a look at this one.

**Comment by KPostOffice** [comment]
Still valid. Looks like an issue with how unresolved packages are parsed from adviser output. They seem to undergo an unnecessary transformation into pipfile requirements before their: name, version, and index are extracted. They should be able to be directly extracted from adviser output though.

**Comment by harshad16** [comment]
Thanks @KPostOffice for taking a look at this issue
