### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by harshad16** [thoth-station/workflow-helpers#358]
**Describe the bug**

Kebechet administrator is failing
workflow-helpers: v0.9.4
```
2021-12-06 21:04:16,437   1 ERROR    thoth.workflow_helpers.common:79: [Errno 2] No such file or directory: '/mnt/workdir/messages_to_be_sent.json'
Traceback (most recent call last):
  File "/opt/app-root/src/thoth/workflow_helpers/common.py", line 72, in store_messages
    with open(MSG_OUT_FILE, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/workdir/messages_to_be_sent.json'
2021-12-06 21:04:16,438   1 CRITICAL root:105: Traceback (most recent call last):
  File "kebechet_administrator.py", line 224, in <module>
    run_kebechet_administrator()
  File "kebechet_administrator.py", line 215, in run_kebechet_administrator
    trigger_message=Configuration.MESSAGE_TYPE.name,
AttributeError: 'str' object has no attribute 'name'
```

**Comment by pacospace** [comment]
Fixed by: https://github.com/thoth-station/workflow-helpers/pull/360
