### ISSUE TITLE
Adviser run workflow fails at trigger-integration.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/workflow-helpers#404]
**Describe the bug**

Observing the following error in the adviser run, trigger-integration test.
```
Traceback (most recent call last):
  File "select_thoth_integration.py", line 63, in <module>
    trigger_integration_workflow()
  File "select_thoth_integration.py", line 44, in trigger_integration_workflow
    f.write(source_type)
TypeError: write() argument must be str, not None
```

```
STEP                                      TEMPLATE                                   PODNAME                                           DURATION  MESSAGE
 ✖ adviser-220727182009-17104de579151285  adviser                                                                                                                         
 ├─✔ advise                               advise/advise                              adviser-220727182009-17104de579151285-839741922   11s                                
 ├─✔ parse-adviser-output                 parse-adviser-output/parse-adviser-output  adviser-220727182009-17104de579151285-93237856    11s                                
 ├─✔ graph-sync-advise(0)                 graph-sync/graph-sync                      adviser-220727182009-17104de579151285-1592980532  11s                                
 ├─✖ trigger-integration                  trigger-integration/trigger-integration    adviser-220727182009-17104de579151285-2904022161  8s        failed with exit code 1  
 └─✔ send-messages                        send-messages/send-messages                adviser-220727182009-17104de579151285-2865606091  6s 
```
Workflow-helper version: v0.9.10

**To Reproduce**
1. Go to khemenu url
2. trigger adviser
3. Scroll down to argo workflow

**Additional context**

**Comment by codificat** [comment]
from today's backlog refine meeting: let's re-verify if this is still valid

if it is still valid, this should be an easy one.

**Comment by harshad16** [comment]
The trigger-integration, with adviser run execution, seems to be working smoothly.
```
STEP                                      TEMPLATE                                   PODNAME                                           DURATION  MESSAGE
 ● adviser-230115080017-ca50227c6e91fa11  adviser                                                                                                                                                      
 ├─✔ advise                               advise/advise                              adviser-230115080017-ca50227c6e91fa11-1816372804  20s                                                             
 ├─● graph-sync-advise                    graph-sync/graph-sync                                                                                                                                        
 │ ├─✖ graph-sync-advise(0)               graph-sync/graph-sync                      adviser-230115080017-ca50227c6e91fa11-1083339018  19s       failed with exit code 1                               
 │ ├─✖ graph-sync-advise(1)               graph-sync/graph-sync                      adviser-230115080017-ca50227c6e91fa11-1552965255  20s       failed with exit code 1                               
 │ ├─✖ graph-sync-advise(2)               graph-sync/graph-sync                      adviser-230115080017-ca50227c6e91fa11-3164057964  17s       failed with exit code 1                               
 │ └─● graph-sync-advise(3)               graph-sync/graph-sync                      adviser-230115080017-ca50227c6e91fa11-1486148969  17s                                                             
 ├─✔ parse-adviser-output                 parse-adviser-output/parse-adviser-output  adviser-230115080017-ca50227c6e91fa11-179257482   27s                                                             
 ├─✔ trigger-integration                  trigger-integration/trigger-integration    adviser-230115080017-ca50227c6e91fa11-4225212995  11s                                                             
 ├─○ kebechet-run-results                 kebechet-run-results/schedule-kebechet                                                                 when '1 == 1 && "CLI" == "KEBECHET"' evaluated false  
 └─✔ send-messages                        send-messages/send-messages                adviser-230115080017-ca50227c6e91fa11-1599742089  8s                                                       
```

Fixed by PR https://github.com/thoth-station/workflow-helpers/pull/405 
Thanks to all who worked on this.
Verified closing it.
