### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/workflow-helpers#92]
```
2020-09-15 19:41:30,649   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
2020-09-15 19:41:30,649   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
2020-09-15 19:41:30,650   1 INFO     thoth.parse_solver_inputs:31: Thoth workflow-helpers task: parse_solver_inputs v0.1.9+thamos.1.0.0.common.0.19.0.python.0.10.1analyzer.0.1.8.storages.0.25.8
2020-09-15 19:41:30,650   1 INFO     thoth.workflow_helpers.common:28: Loading document from a local file: '/mnt/component/document/solver-fedora-32-py37-1337e446'
2020-09-15 19:41:30,654   1 CRITICAL root:102: Traceback (most recent call last):
  File "parse_solver_inputs.py", line 69, in <module>
    parse_solver_inputs()
  File "parse_solver_inputs.py", line 54, in parse_solver_inputs
    "package_version": {"type": "str", "value": package_inputs[1]},
IndexError: list index out of range
```

**Comment by bissenbay** [comment]
https://github.com/thoth-station/workflow-helpers/issues/106
